FROM phusion/baseimage:0.11

RUN apt-get update -qq && apt-get install -y \
    systemd-coredump \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 3030 24567

COPY scripts/run_docker.sh /usr/local/bin/run.sh
COPY docker-build/near /usr/local/bin/near

ENTRYPOINT ["/sbin/my_init", "--"]

CMD ["/usr/local/bin/run.sh"]
