{
 "title": "nearcore",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Blocks Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "block_num_processed", "legendFormat": "TotalBlocksProcessed" },
    {
     "expr": "block_num_processed_successfully",
     "legendFormat": "BlocksProcessSuccessfully"
    }
   ]
  },
  {
   "title": "Average Block Processing Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(block_processing_time_sum / block_processing_time_count) * 1000"
    }
   ]
  },
  {
   "title": "Blocks Produced",
   "type": "graph",
   "description": "The number of blocks produced by this node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "block_num_produced", "legendFormat": "BlocksProduced" }
   ]
  },
  {
   "title": "Block Height",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "head_block_height" }
   ]
  },
  {
   "title": "HTTP RPC Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "http_rpc_requests_total" }
   ]
  },
  {
   "title": "HTTP Status Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "http_status_request_total" }
   ]
  },
  {
   "title": "HTTP Prometheus Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "http_prometheus_requests_total" }
   ]
  }
 ]
}