#!/bin/bash
set -e

IMAGE=${!:-nearmint}
STUDIO_IMAGE=${2:-nearprotocol/studio:0.1.8}
TOTAL_NODES=2

sudo docker run -d --name testnet-0 -p 3030:3030 -p 26656:26656 \
	-e "BOOT_NODES=127.0.0.1:26658" \
	-e "NODE_ID=0" \
	-e "TOTAL_NODES=${TOTAL_NODES}" \
	-e "NODE_KEY=53Mr7IhcJXu3019FX+Ra+VbxSQ5y2q+pknmM463jzoFzldWZb16dSYRxrhYrLRXe/UA0wR2zFy4c3fY5yDHjlA==" \
	${IMAGE}

sudo docker run -d --name testnet-1 -p 3031:3030 -p 26670:26656 \
	-e "BOOT_NODES=6f99d7b49a10fff319cd8bbbd13c3a964dcd0248@172.17.0.2:26656" \
	-e "NODE_ID=1" \
	-e "TOTAL_NODES=${TOTAL_NODES}" \
	${IMAGE}

