#!/bin/bash
set -e

IMAGE=${1:-nearmint_test4}
TOTAL_NODES=4
NODE_ID=0
RPC_PORT=3030
P2P_PORT=26656

sudo docker run -d --name testnet-${NODE_ID} -p ${RPC_PORT}:3030 -p ${P2P_PORT}:26656 \
	-e "NODE_ID=${NODE_ID}" \
	-e "TOTAL_NODES=${TOTAL_NODES}" \
	-e "NODE_KEY=53Mr7IhcJXu3019FX+Ra+VbxSQ5y2q+pknmM463jzoFzldWZb16dSYRxrhYrLRXe/UA0wR2zFy4c3fY5yDHjlA==" \
	${IMAGE}

while [[ ${NODE_ID} -lt $((${TOTAL_NODES} - 1)) ]]; do
let NODE_ID=NODE_ID+1
let RPC_PORT=RPC_PORT+1
let P2P_PORT=P2P_PORT+1
sudo docker run -d --name testnet-${NODE_ID} -p ${RPC_PORT}:3030 -p ${P2P_PORT}:26656 \
	-e "BOOT_NODES=6f99d7b49a10fff319cd8bbbd13c3a964dcd0248@172.17.0.2:26656" \
	-e "NODE_ID=${NODE_ID}" \
	-e "TOTAL_NODES=${TOTAL_NODES}" \
	${IMAGE}
done

