#!/bin/bash
set -e

if [[ -z ${CHAIN_SPEC_PATH} ]]
then
	generate-test-spec -n ${TOTAL_NODES} -c ${TMHOME}/chain_spec.json
	CHAIN_SPEC_PATH="${TMHOME}/chain_spec.json"
fi

if [[ -z ${KEYGEN_SEED} ]] 
then
	KEYGEN_SEED="near.${NODE_ID}"
fi

keystore keygen --tendermint --test-seed ${KEYGEN_SEED} -p ${TMHOME}/config/

if [[ -n ${NODE_KEY} ]]
then
    cat << EOF > ${TMHOME}/config/node_key.json
{"priv_key": {"type": "tendermint/PrivKeyEd25519", "value": "$NODE_KEY"}}
EOF
	cat ${TMHOME}/config/node_key.json
fi

echo "Chain spec ${CHAIN_SPEC_PATH} with ${TOTAL_NODES}"
echo "Keygen: ${KEYGEN_SEED}"
echo "Bootnode: ${BOOT_NODES}"

tendermint node --p2p.persistent_peers="${BOOT_NODES}" &

nearmint --abci-address 127.0.0.1:26658 --chain-spec-file=${CHAIN_SPEC_PATH} --base-path=${TMHOME}

