@startuml

' Use PlantUML plugin to view: https://plugins.jetbrains.com/plugin/7017-plantuml-integration
' See syntax here: http://plantuml.com/component-diagram

[Storage]

component Client {
   component BeaconClient {
        [BlockChain<SignedBeaconBlock>] as BeaconChain
        [Authority]
        }

   component ShardClient {
     [Runtime]
     [Trie]
     [BlockChain<SignedShardBlock>] as ShardChain
   }
   ShardClient -- prepare_new_block
   ShardClient -- insert_block
   ShardClient -- apply_block

   package RPCInterfaces {
   TrieUpdate -- Trie
   TrieViewer -- ShardClient
   }
}

Client -- produce_block
Client -- import_block

Storage #-- ShardChain
Storage #-- BeaconChain
Storage #-- ShardClient


package Coroutines {
    [BlockProducer] --> produce_block
    [BlockImporter] --> import_block
}


[RPC]
RPC --> TrieViewer
RPC --> TrieUpdate
Client #-- RPC

@enduml
