#!/bin/bash
set -e

BASE_PATH=/srv/near

mkdir -p ${BASE_PATH}

if [[ -z ${CHAIN_SPEC_PATH} ]]
then
generate-test-spec -n ${TOTAL_NODES} -c ${BASE_PATH}/chain_spec.json
CHAIN_SPEC_PATH="${BASE_PATH}/chain_spec.json"
fi

if [[ -z ${KEYGEN_SEED} ]]
then
KEYGEN_SEED="near.${NODE_NUM}"
fi
keystore keygen --test-seed ${KEYGEN_SEED} -p ${BASE_PATH}/storage/keystore

alphanet --base-path ${BASE_PATH} \
    --chain-spec-file ${CHAIN_SPEC_PATH} \
    --addr 0.0.0.0:3000 \
    --test-network-key-seed ${NODE_NUM} \
    --account-id near.${NODE_NUM} \
    --boot-nodes ${BOOT_NODE_IP}:3000/7tkzFg8RHBmMw1ncRJZCCZAizgq4rwCftTKYLce8RU8t 2>&1 | tee output.log
